### ISSUE TITLE
一直卡在validation那里

### ISSUE THREAD

**Issue by hfdzlsw** [bubbliiiing/Siamese-pytorch#34]
大佬，这种情况是什么问题，一直卡在这里不动
![image](https://github.com/bubbliiiing/Siamese-pytorch/assets/11845565/bc2da34d-23cf-41d4-8d65-6f845041819d)

**Comment by hfdzlsw** [comment]
看了下是在for iteration, batch in enumerate(genval)这步卡住了

**Comment by hfdzlsw** [comment]
将num_workers设置为0也没用

**Comment by bubbliiiing** [comment]
看不出来
你能去dataset里面打印一下吗

**Comment by hfdzlsw** [comment]
> 看不出来 你能去dataset里面打印一下吗

这是列表页
![image](https://github.com/bubbliiiing/Siamese-pytorch/assets/11845565/2fa347f6-27a1-43e6-9a57-dcc0771d48e1)
里面的内容是这样
![image](https://github.com/bubbliiiing/Siamese-pytorch/assets/11845565/646017ef-1ab3-40ff-af83-aba8f27d7a34)

**Comment by hfdzlsw** [comment]
找到原因了，因为我有些类别里面的图片只有2张，导致运行到下面这段代码后一直while循环不退出。。
![image](https://github.com/bubbliiiing/Siamese-pytorch/assets/11845565/ea79593c-a216-44ee-bede-db5669417755)

**Comment by bubbliiiing** [comment]
嗯是的
