### ISSUE TITLE
指定model_path 为 vgg16-397923af.pth 报错 KeyError

### ISSUE THREAD

**Issue by ZhangYFeng** [bubbliiiing/Siamese-pytorch#7]
将 model_path 指定为  vgg16-397923af.pth 报错 KeyError，调试后，发现 vgg16-397923af.pth数据与模型不匹配，是否vgg16-397923af.pth没有更新？还是我不能这样使用呢？

**Comment by wenjingyi** [comment]
同问

**Comment by bubbliiiing** [comment]
看注释了么
